// Generated by scripts/setup-cash.mjs. The devnet test dollar cash orders and plans pay with.
export const CASH_MINT = "3uhU48V1AH8zCRms2UmmbSLvSiHGU4hgf1nUGh6Xk8QK";
export const CASH_DECIMALS = 6;
export const CASH_TOKEN_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
