// Generated by scripts/sync-deployments.mjs. Do not edit.
import robinhoodTestnet from "./robinhoodTestnet.json";
import tempoTestnet from "./tempoTestnet.json";

export const DEPLOYMENTS = [robinhoodTestnet, tempoTestnet] as const;
