// Generated by scripts/sync-deployments.mjs. Do not edit.
import arbitrumSepolia from "./arbitrumSepolia.json";
import baseSepolia from "./baseSepolia.json";
import bridges from "./bridges.json";
import robinhoodTestnet from "./robinhoodTestnet.json";
import sepolia from "./sepolia.json";
import tempoTestnet from "./tempoTestnet.json";

export const DEPLOYMENTS = [arbitrumSepolia, baseSepolia, bridges, robinhoodTestnet, sepolia, tempoTestnet] as const;
