/**
 * The test dollar: a devnet stand-in for USDC that cash orders and monthly plans
 * pay with.
 *
 * Token-2022, 6 decimals like USDC, with on-chain metadata so wallets show
 * "USDC (Sheaf devnet)". Mint authority is the faucet key, so the app can hand a
 * visitor test dollars the same way it hands out test stocks. Real USDC is never
 * involved: everything that settles is on devnet.
 *
 *   node scripts/setup-cash.mjs --url devnet
 *
 * Writes web/lib/cash.generated.ts.
 */
import fs from "node:fs";
import path from "node:path";
import {
  Connection,
  Keypair,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";
import {
  TOKEN_2022_PROGRAM_ID,
  ExtensionType,
  getMintLen,
  createInitializeMetadataPointerInstruction,
  createInitializeMintInstruction,
  TYPE_SIZE,
  LENGTH_SIZE,
} from "@solana/spl-token";
import { createRequire } from "node:module";

// spl-token-metadata is a dependency of spl-token; resolve it from there.
const fromHere = createRequire(import.meta.url);
const { createInitializeInstruction, pack } = createRequire(fromHere.resolve("@solana/spl-token"))("@solana/spl-token-metadata");

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const urlArg = process.argv.includes("--url") ? process.argv[process.argv.indexOf("--url") + 1] : "devnet";
const RPC = urlArg === "devnet" ? (process.env.WRITE_RPC || "https://api.devnet.solana.com") : urlArg;

function readEnv(file) {
  const out = {};
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]] = m[2].replace(/^"|"$/g, "");
  }
  return out;
}

const env = readEnv(path.join(ROOT, "web", ".env.local"));
const secret = env.FAUCET_SECRET_KEY;
const faucet = secret.trim().startsWith("[")
  ? Keypair.fromSecretKey(Uint8Array.from(JSON.parse(secret)))
  : Keypair.fromSecretKey((await import("bs58")).default.decode(secret.trim()));

const connection = new Connection(env.HELIUS_API_KEY ? `https://devnet.helius-rpc.com/?api-key=${env.HELIUS_API_KEY}` : RPC, "confirmed");

const mint = Keypair.generate();
const metadata = {
  mint: mint.publicKey,
  name: "USDC (Sheaf devnet)",
  symbol: "USDC",
  uri: "",
  additionalMetadata: [["note", "Devnet test dollar for Sheaf. Not USDC, worth nothing."]],
};
const mintLen = getMintLen([ExtensionType.MetadataPointer]);
const metaLen = TYPE_SIZE + LENGTH_SIZE + pack(metadata).length;
const lamports = await connection.getMinimumBalanceForRentExemption(mintLen + metaLen);

const tx = new Transaction().add(
  SystemProgram.createAccount({
    fromPubkey: faucet.publicKey,
    newAccountPubkey: mint.publicKey,
    space: mintLen,
    lamports,
    programId: TOKEN_2022_PROGRAM_ID,
  }),
  createInitializeMetadataPointerInstruction(mint.publicKey, faucet.publicKey, mint.publicKey, TOKEN_2022_PROGRAM_ID),
  createInitializeMintInstruction(mint.publicKey, 6, faucet.publicKey, null, TOKEN_2022_PROGRAM_ID),
  createInitializeInstruction({
    programId: TOKEN_2022_PROGRAM_ID,
    metadata: mint.publicKey,
    updateAuthority: faucet.publicKey,
    mint: mint.publicKey,
    mintAuthority: faucet.publicKey,
    name: metadata.name,
    symbol: metadata.symbol,
    uri: metadata.uri,
  }),
);
const sig = await sendAndConfirmTransaction(connection, tx, [faucet, mint]);
console.log("cash mint", mint.publicKey.toBase58(), sig);

fs.writeFileSync(
  path.join(ROOT, "web", "lib", "cash.generated.ts"),
  `// Generated by scripts/setup-cash.mjs. The devnet test dollar cash orders and plans pay with.\n` +
    `export const CASH_MINT = "${mint.publicKey.toBase58()}";\n` +
    `export const CASH_DECIMALS = 6;\n` +
    `export const CASH_TOKEN_PROGRAM = "${TOKEN_2022_PROGRAM_ID.toBase58()}";\n`,
);
